# Generated by Django 4.1.5 on 2023-03-25 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 25, 16, 30, 40, 548779)),
        ),
    ]
