# Generated by Django 4.1.5 on 2023-02-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_mst_table',
            name='Product_image',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
