# Generated by Django 4.1.5 on 2023-02-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_mst_table_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_mst_table',
            name='Product_image',
        ),
    ]
