# Generated by Django 4.1.5 on 2023-02-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_product_mst_table_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_mst_table',
            name='Product_image',
            field=models.ImageField(default='null', upload_to='static/images/'),
        ),
    ]
