# Generated by Django 4.1.5 on 2023-02-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_product_mst_table_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_mst_table',
            name='Product_ram',
            field=models.CharField(default='null', max_length=12),
        ),
    ]
