# Generated by Django 4.1.5 on 2023-02-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_mst_table_product_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_mst_table',
            name='Product_details',
            field=models.TextField(default='none'),
        ),
    ]
