# Generated by Django 4.1.5 on 2023-03-03 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 3, 18, 23, 32, 927881))),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
