# Generated by Django 4.1.5 on 2023-03-04 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_members_model_alter_signup_model_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_model',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='members_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 14, 31, 1, 135593)),
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 14, 31, 1, 134644)),
        ),
    ]
