# Generated by Django 4.1.5 on 2023-03-05 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_members_model_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 40, 29, 804680)),
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 40, 29, 804680)),
        ),
    ]
