# Generated by Django 4.1.5 on 2023-03-05 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_members_model_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chairmans_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 45, 36, 378032))),
            ],
        ),
        migrations.CreateModel(
            name='events_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 45, 36, 378032))),
            ],
        ),
        migrations.CreateModel(
            name='notices_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 45, 36, 379032))),
            ],
        ),
        migrations.CreateModel(
            name='notices_view_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 45, 36, 379032))),
            ],
        ),
        migrations.CreateModel(
            name='transactions_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 45, 36, 379032))),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 45, 36, 379032))),
            ],
        ),
        migrations.CreateModel(
            name='visitors_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 45, 36, 379032))),
            ],
        ),
        migrations.CreateModel(
            name='watchmans_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 45, 36, 380032))),
            ],
        ),
        migrations.AlterField(
            model_name='members_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 45, 36, 380032)),
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 9, 45, 36, 380032)),
        ),
    ]
