# Generated by Django 4.1.5 on 2023-03-05 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_chairmans_model_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_model',
            name='comments',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='events_model',
            name='event_img',
            field=models.FileField(blank=True, upload_to='static/upload'),
        ),
        migrations.AddField(
            model_name='events_model',
            name='event_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='events_model',
            name='event_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='events_model',
            name='event_time',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 39232)),
        ),
        migrations.AlterField(
            model_name='chairmans_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 39232)),
        ),
        migrations.AlterField(
            model_name='events_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 39232)),
        ),
        migrations.AlterField(
            model_name='members_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 41555)),
        ),
        migrations.AlterField(
            model_name='notices_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 40232)),
        ),
        migrations.AlterField(
            model_name='notices_view_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 39232)),
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 41232)),
        ),
        migrations.AlterField(
            model_name='transactions_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 40232)),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 40232)),
        ),
        migrations.AlterField(
            model_name='visitors_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 40232)),
        ),
        migrations.AlterField(
            model_name='watchmans_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 10, 55, 20, 40232)),
        ),
    ]
