# Generated by Django 4.1.5 on 2023-01-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
